// File generated by Antigravity but requires manual configuration if flutterfire CLI is not used.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for the current platform.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlNVWOO-dZ2fSahzKHbNwW_TKm-JerV_8',
    appId: '1:833190075426:web:705f11d51565a9df2afe7b',
    messagingSenderId: '833190075426',
    projectId: 'gridmaster-3b11e',
    authDomain: 'gridmaster-3b11e.firebaseapp.com',
    storageBucket: 'gridmaster-3b11e.firebasestorage.app',
    measurementId: 'G-PSW42EY9BF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlNVWOO-dZ2fSahzKHbNwW_TKm-JerV_8',
    appId: '1:833190075426:web:705f11d51565a9df2afe7b',
    messagingSenderId: '833190075426',
    projectId: 'gridmaster-3b11e',
    storageBucket: 'gridmaster-3b11e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlNVWOO-dZ2fSahzKHbNwW_TKm-JerV_8',
    appId: '1:833190075426:web:705f11d51565a9df2afe7b',
    messagingSenderId: '833190075426',
    projectId: 'gridmaster-3b11e',
    storageBucket: 'gridmaster-3b11e.firebasestorage.app',
    iosBundleId: 'com.example.gridMaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlNVWOO-dZ2fSahzKHbNwW_TKm-JerV_8',
    appId: '1:833190075426:web:705f11d51565a9df2afe7b',
    messagingSenderId: '833190075426',
    projectId: 'gridmaster-3b11e',
    authDomain: 'gridmaster-3b11e.firebaseapp.com',
    storageBucket: 'gridmaster-3b11e.firebasestorage.app',
  );
}
